/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import ConnectionDB.ConnectDB;
import DAO.CongNhan_DAO;
import DAO.NhanVien_DAO;
import Entity.NhanVien;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author December
 */
public class QuenMatKhauView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    private NhanVien_DAO nhanVien_DAO;
    private CongNhan_DAO congNhan_DAO;
    private ArrayList<String> ngonNguList;

    public QuenMatKhauView() {
        ngonNguList = new ArrayList<>();
        ngonNguList.add("./config/VietNam.properties");
        ngonNguList.add("./config/English.properties");
        initComponents();
        gui();
        try {
            ConnectionDB.ConnectDB.getInstance().connect();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        congNhan_DAO = new CongNhan_DAO();
        nhanVien_DAO = new NhanVien_DAO();
        lblErrTel.setText("");
        lblErrUserName.setText("");
    }

    public void caiDatNgonNguChoView(String fileName) throws FileNotFoundException, IOException {
        FileInputStream fis = new FileInputStream(fileName);
        Properties prop = new Properties();
        prop.load(fis);
//        lblTieuDeDangNhap.setText(prop.getProperty("Login_lblTieuDeDangNhap"));
//        lblTenDangNhap.setText(prop.getProperty("Login_lblTenDangNhap"));
//        lblMatKhau.setText(prop.getProperty("Login_lblMatKhau"));
//        btnDangNhap.setText(prop.getProperty("Login_btnDangNhap"));
    }

    public void gui() {
        this.txtUserName.setBackground(new Color(0, 0, 0, 1));
        this.txtTel.setBackground(new Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblQuenMatKhau = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        lblSoDienThoaiDangKy = new javax.swing.JLabel();
        btnGuiMa = new javax.swing.JButton();
        txtTel = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        lblErrUserName = new javax.swing.JLabel();
        lblErrTel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblQuenMatKhau1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên tài khoản:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_user_20px_1.png"))); // NOI18N

        jLabel8.setText("_______________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 25, 28));
        jPanel2.setPreferredSize(new java.awt.Dimension(550, 350));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau.setText("THVT-SHOES");
        lblQuenMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 730, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        lblTenDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(230, 230, 217));
        lblTenDangNhap.setText("UserName");
        jPanel2.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 360, -1));

        lblSoDienThoaiDangKy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSoDienThoaiDangKy.setForeground(new java.awt.Color(230, 230, 217));
        lblSoDienThoaiDangKy.setText("Tel contact");
        jPanel2.add(lblSoDienThoaiDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 360, -1));

        btnGuiMa.setBackground(new java.awt.Color(224, 48, 48));
        btnGuiMa.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btnGuiMa.setForeground(new java.awt.Color(255, 255, 255));
        btnGuiMa.setText(" Send reset code");
        btnGuiMa.setActionCommand("Gửi mã");
        btnGuiMa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMaActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 520, 80));

        txtTel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTel.setForeground(new java.awt.Color(255, 255, 255));
        txtTel.setBorder(null);
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 510, 30));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 500, 30));

        lblErrUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErrUserName.setForeground(new java.awt.Color(241, 42, 34));
        lblErrUserName.setText("đây là dòng thông báo lỗi");
        jPanel2.add(lblErrUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 500, -1));

        lblErrTel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErrTel.setForeground(new java.awt.Color(241, 42, 34));
        lblErrTel.setText("đây là dòng thông báo lỗi");
        jPanel2.add(lblErrTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 510, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 520, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 520, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 230, 217));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Can’t remember your password? Enter your username and password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 730, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 217));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("and we will send you an random code to create a new password.");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 730, -1));

        lblQuenMatKhau1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblQuenMatKhau1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau1.setText("Reset your password");
        lblQuenMatKhau1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblQuenMatKhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 730, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 600));

        setSize(new java.awt.Dimension(731, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMaActionPerformed
        String maNhanVien = this.txtUserName.getText();
        String soDienThoai = this.txtTel.getText();
        NhanVien_DAO nhanVienDao = new NhanVien_DAO();
        boolean flag = true;
        if (maNhanVien.trim().replaceAll(" ", "").equals("")) {
            lblErrUserName.setText("UserName is required");
            flag = false;
        } else {
            lblErrUserName.setText("");
        }
        if (maNhanVien.trim().replaceAll(" ", "").equals("")) {
            lblErrTel.setText("Please enter a phone number");
            flag = false;
        } else {
            lblErrTel.setText("");
        }
        if (flag) {
            NhanVien nhanVien = nhanVien_DAO.layMotNhanVienTheoMaNhanVien(maNhanVien);
            if (nhanVien!=null && nhanVien.getSoDienThoai().equalsIgnoreCase(soDienThoai)) {
                try {
                    Random random = new Random();
                    int newPassWord = random.nextInt(999999 + 1 - 100000) + 100000;
                    System.out.println(newPassWord);
                    nhanVien.setMatKhau(newPassWord + "");
                    if (nhanVien_DAO.suaThongTinMotNhanVien(nhanVien)) {
                        String username = "admin";
                        String password = "123456";
                        String to = soDienThoai;
                        String message = "Mật khẩu mới của bạn: " + newPassWord;
                        String requestUrl = "http://localhost:9710/http/send-message?"
                                + "username=" + URLEncoder.encode(username, "UTF-8")
                                + "&password=" + URLEncoder.encode(password, "UTF-8")
                                + "&to=" + URLEncoder.encode(to, "UTF-8")
                                + "&message-type=sms.automatic"
                                + "&message=" + URLEncoder.encode(message, "UTF-8");
                        URL url = new URL(requestUrl);
                        HttpURLConnection uc = (HttpURLConnection) url.openConnection();
                        System.out.println(uc.getResponseMessage());
                        uc.disconnect();
                        this.dispose();
                        new NhapMaXacNhanView(nhanVien).setVisible(true);
                    }
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                }
            } else {
                lblErrTel.setText("Phone number incorrect");
            }
        }
    }//GEN-LAST:event_btnGuiMaActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhauView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblErrTel;
    private javax.swing.JLabel lblErrUserName;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblQuenMatKhau1;
    private javax.swing.JLabel lblSoDienThoaiDangKy;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
