/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.io.File;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Student
 */
public class CapNhatCongNhanView extends javax.swing.JFrame {

    /**
     * Creates new form modalThemNhanSuView
     */
    public CapNhatCongNhanView() {
        initComponents();
        init();
    }

    public void init() {
        this.txtMaCongNha.setText("");
        this.lbErrMaCongNhan.setText("");
        this.txtHoVaTen.setText("");
        this.lbErrHovaTen.setText("");
        this.txtSoCCCD.setText("");
        this.lbErrSoCCCD.setText("");
        this.txtEmail.setText("");
        this.lbErrEmail.setText("");
        this.txtSoDienThoaiNhanVien.setText("");
        this.lbErrSoDienThoai.setText("");
        this.lbErrSoCCCD.setText("");
        this.txtDiaChi.setText("");
        this.lbErrDiaChi.setText("");
        this.rdNam.setSelected(true);
        this.txtDiaChi.setText("");
//        this.txtLuongNhanVien.setText("");
//        this.lbErrLuongNhanVien.setText("");

        this.txtMaCongNha.setBackground(new Color(0, 0, 0, 1));
        this.txtHoVaTen.setBackground(new Color(0, 0, 0, 1));
        this.txtSoCCCD.setBackground(new Color(0, 0, 0, 1));
        this.txtEmail.setBackground(new Color(0, 0, 0, 1));
        this.txtSoDienThoaiNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtDiaChi.setBackground(new Color(0, 0, 0, 1));
//        this.txtLuongNhanVien.setBackground(new Color(0,0,0,1));
        
        ButtonGroup btngroup = new ButtonGroup();
        btngroup.add(this.rdNam);
        btngroup.add(this.rdNu);
        
        
        this.jDateNgayVaoLam.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder1 = new CustomView.PanelBorder();
        lbCapNhatCongNhan = new javax.swing.JLabel();
        lbExitModal = new javax.swing.JLabel();
        lbMaCongNhan = new javax.swing.JLabel();
        lbGachChanMaNhanVien = new javax.swing.JLabel();
        txtMaCongNha = new javax.swing.JTextField();
        lbErrMaCongNhan = new javax.swing.JLabel();
        lbHoVaTen = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        lbGachChanHoVaTenNhanVien = new javax.swing.JLabel();
        lbAnhDaiDienNhanVien = new javax.swing.JLabel();
        lbErrHovaTen = new javax.swing.JLabel();
        lbSoCCCD = new javax.swing.JLabel();
        txtSoCCCD = new javax.swing.JTextField();
        lbGachChanSoCCCDNhanVien = new javax.swing.JLabel();
        btnAnhDaiDien = new javax.swing.JButton();
        lbErrSoCCCD = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbGachChanEmailNhanVien = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbSoDienThoaiNhanVien = new javax.swing.JLabel();
        lbErrEmail = new javax.swing.JLabel();
        txtSoDienThoaiNhanVien = new javax.swing.JTextField();
        lbGachChanSoDienThoaiNhanVien = new javax.swing.JLabel();
        lbErrSoDienThoai = new javax.swing.JLabel();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbErrDiaChi = new javax.swing.JLabel();
        lbGachChanDiaChiNhanVien1 = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jdateNgaySinh = new com.toedter.calendar.JDateChooser();
        lbNgaySinh = new javax.swing.JLabel();
        lbToNhom = new javax.swing.JLabel();
        cbPhongBanNhanVien = new javax.swing.JComboBox<>();
        cbChucVuNhanVien = new javax.swing.JComboBox<>();
        lbChucVu = new javax.swing.JLabel();
        lbNgayVaoLam = new javax.swing.JLabel();
        jDateNgayVaoLam = new com.toedter.calendar.JDateChooser();
        btnLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(204, 102, 255));

        lbCapNhatCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbCapNhatCongNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCapNhatCongNhan.setText("Cập nhật công nhân");
        panelBorder1.add(lbCapNhatCongNhan);
        lbCapNhatCongNhan.setBounds(40, 10, 620, 50);

        lbExitModal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        lbExitModal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExitModal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitModalMouseClicked(evt);
            }
        });
        panelBorder1.add(lbExitModal);
        lbExitModal.setBounds(660, 20, 30, 30);

        lbMaCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMaCongNhan.setText("Mã công nhân");
        panelBorder1.add(lbMaCongNhan);
        lbMaCongNhan.setBounds(200, 90, 180, 18);

        lbGachChanMaNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanMaNhanVien);
        lbGachChanMaNhanVien.setBounds(380, 100, 273, 16);

        txtMaCongNha.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaCongNha.setText("jTextField1");
        txtMaCongNha.setBorder(null);
        txtMaCongNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCongNhaActionPerformed(evt);
            }
        });
        panelBorder1.add(txtMaCongNha);
        txtMaCongNha.setBounds(380, 90, 270, 20);

        lbErrMaCongNhan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrMaCongNhan.setForeground(new java.awt.Color(204, 0, 0));
        lbErrMaCongNhan.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrMaCongNhan);
        lbErrMaCongNhan.setBounds(380, 120, 230, 20);

        lbHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbHoVaTen.setText("Họ và tên:");
        panelBorder1.add(lbHoVaTen);
        lbHoVaTen.setBounds(200, 150, 180, 20);

        txtHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtHoVaTen.setText("jTextField1");
        txtHoVaTen.setBorder(null);
        txtHoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoVaTenActionPerformed(evt);
            }
        });
        panelBorder1.add(txtHoVaTen);
        txtHoVaTen.setBounds(380, 150, 270, 20);

        lbGachChanHoVaTenNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanHoVaTenNhanVien);
        lbGachChanHoVaTenNhanVien.setBounds(380, 160, 273, 16);

        lbAnhDaiDienNhanVien.setBackground(new java.awt.Color(153, 0, 0));
        lbAnhDaiDienNhanVien.setForeground(new java.awt.Color(255, 0, 51));
        lbAnhDaiDienNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/female.png"))); // NOI18N
        panelBorder1.add(lbAnhDaiDienNhanVien);
        lbAnhDaiDienNhanVien.setBounds(20, 130, 140, 160);

        lbErrHovaTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrHovaTen.setForeground(new java.awt.Color(204, 0, 0));
        lbErrHovaTen.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrHovaTen);
        lbErrHovaTen.setBounds(380, 180, 230, 18);

        lbSoCCCD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbSoCCCD.setText("Số CCCD:");
        panelBorder1.add(lbSoCCCD);
        lbSoCCCD.setBounds(200, 210, 170, 18);

        txtSoCCCD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSoCCCD.setText("jTextField1");
        txtSoCCCD.setBorder(null);
        txtSoCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoCCCDActionPerformed(evt);
            }
        });
        panelBorder1.add(txtSoCCCD);
        txtSoCCCD.setBounds(380, 210, 270, 20);

        lbGachChanSoCCCDNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanSoCCCDNhanVien);
        lbGachChanSoCCCDNhanVien.setBounds(380, 220, 273, 16);

        btnAnhDaiDien.setText("Ảnh đại diện");
        btnAnhDaiDien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnhDaiDien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhDaiDienActionPerformed(evt);
            }
        });
        panelBorder1.add(btnAnhDaiDien);
        btnAnhDaiDien.setBounds(30, 300, 103, 25);

        lbErrSoCCCD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrSoCCCD.setForeground(new java.awt.Color(204, 0, 0));
        lbErrSoCCCD.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrSoCCCD);
        lbErrSoCCCD.setBounds(380, 240, 230, 18);

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbEmail.setText("Email:");
        panelBorder1.add(lbEmail);
        lbEmail.setBounds(200, 270, 180, 18);

        lbGachChanEmailNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanEmailNhanVien);
        lbGachChanEmailNhanVien.setBounds(380, 280, 273, 16);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setText("jTextField1");
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        panelBorder1.add(txtEmail);
        txtEmail.setBounds(380, 270, 270, 20);

        lbSoDienThoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbSoDienThoaiNhanVien.setText("Số điện thoại");
        panelBorder1.add(lbSoDienThoaiNhanVien);
        lbSoDienThoaiNhanVien.setBounds(200, 330, 180, 18);

        lbErrEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrEmail.setForeground(new java.awt.Color(204, 0, 0));
        lbErrEmail.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrEmail);
        lbErrEmail.setBounds(380, 300, 230, 18);

        txtSoDienThoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSoDienThoaiNhanVien.setText("jTextField1");
        txtSoDienThoaiNhanVien.setBorder(null);
        txtSoDienThoaiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtSoDienThoaiNhanVien);
        txtSoDienThoaiNhanVien.setBounds(380, 330, 270, 20);

        lbGachChanSoDienThoaiNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanSoDienThoaiNhanVien);
        lbGachChanSoDienThoaiNhanVien.setBounds(380, 340, 273, 16);

        lbErrSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrSoDienThoai.setForeground(new java.awt.Color(204, 0, 0));
        lbErrSoDienThoai.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrSoDienThoai);
        lbErrSoDienThoai.setBounds(380, 360, 230, 18);

        lbDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbDiaChi.setText("Địa chỉ thường chú:");
        panelBorder1.add(lbDiaChi);
        lbDiaChi.setBounds(200, 390, 180, 18);

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDiaChi.setText("jTextField1");
        txtDiaChi.setBorder(null);
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        panelBorder1.add(txtDiaChi);
        txtDiaChi.setBounds(380, 390, 270, 20);

        lbErrDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrDiaChi.setForeground(new java.awt.Color(204, 0, 0));
        lbErrDiaChi.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrDiaChi);
        lbErrDiaChi.setBounds(380, 420, 230, 18);

        lbGachChanDiaChiNhanVien1.setText("_______________________________________");
        panelBorder1.add(lbGachChanDiaChiNhanVien1);
        lbGachChanDiaChiNhanVien1.setBounds(380, 400, 273, 16);

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbGioiTinh.setText("Giới tính:");
        panelBorder1.add(lbGioiTinh);
        lbGioiTinh.setBounds(200, 450, 180, 20);

        rdNam.setText("Nam");
        rdNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });
        panelBorder1.add(rdNam);
        rdNam.setBounds(380, 450, 60, 25);

        rdNu.setText("Nữ");
        rdNu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed(evt);
            }
        });
        panelBorder1.add(rdNu);
        rdNu.setBounds(470, 450, 60, 25);

        jdateNgaySinh.setDateFormatString("yyyy-MM-dd");
        panelBorder1.add(jdateNgaySinh);
        jdateNgaySinh.setBounds(380, 490, 270, 30);

        lbNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgaySinh.setText("Ngày sinh:");
        panelBorder1.add(lbNgaySinh);
        lbNgaySinh.setBounds(200, 500, 120, 18);

        lbToNhom.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbToNhom.setText("Tổ/Nhóm");
        panelBorder1.add(lbToNhom);
        lbToNhom.setBounds(200, 530, 130, 30);

        cbPhongBanNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng tài chính", "Phòng kinh doanh", "Phòng nhân sự" }));
        cbPhongBanNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBorder1.add(cbPhongBanNhanVien);
        cbPhongBanNhanVien.setBounds(380, 530, 270, 30);

        cbChucVuNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));
        cbChucVuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbChucVuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChucVuNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(cbChucVuNhanVien);
        cbChucVuNhanVien.setBounds(380, 570, 270, 30);

        lbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbChucVu.setText("Chức vụ:");
        panelBorder1.add(lbChucVu);
        lbChucVu.setBounds(200, 570, 120, 30);

        lbNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgayVaoLam.setText("Ngày vào làm:");
        panelBorder1.add(lbNgayVaoLam);
        lbNgayVaoLam.setBounds(200, 610, 130, 30);

        jDateNgayVaoLam.setDateFormatString("yyyy-MM-dd");
        panelBorder1.add(jDateNgayVaoLam);
        jDateNgayVaoLam.setBounds(380, 610, 270, 30);

        btnLuu.setBackground(new java.awt.Color(39, 174, 96));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setBorder(null);
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBorder1.add(btnLuu);
        btnLuu.setBounds(190, 670, 130, 40);

        btnThoat.setBackground(new java.awt.Color(231, 76, 60));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setBorder(null);
        btnThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        panelBorder1.add(btnThoat);
        btnThoat.setBounds(410, 670, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(719, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaCongNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCongNhaActionPerformed

    }//GEN-LAST:event_txtMaCongNhaActionPerformed

    private void txtHoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoVaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoVaTenActionPerformed

    private void txtSoCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoCCCDActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSoDienThoaiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiNhanVienActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void rdNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNuActionPerformed

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNamActionPerformed

    private void cbChucVuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChucVuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChucVuNhanVienActionPerformed

    private void lbExitModalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitModalMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbExitModalMouseClicked

    private void btnAnhDaiDienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhDaiDienActionPerformed
        JFileChooser fileChooser = new JFileChooser("d:");
//        int respone=fileChooser.showOpenDialog(null);
        fileChooser.setCurrentDirectory(new File(".\\src\\image"));
        int respone=fileChooser.showSaveDialog(null);
        if(respone== JFileChooser.APPROVE_OPTION ){
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            System.out.println(file);
            String path = file.toString().split("src")[1].replace('\\', '/');
            System.out.println("path file split: "+file.toString().split("src")[1]);
            this.lbAnhDaiDienNhanVien.setIcon(new ImageIcon(this.getClass().getResource(path)));
            System.out.println(this.lbAnhDaiDienNhanVien.getIcon().toString());
        }
    }//GEN-LAST:event_btnAnhDaiDienActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if(evt.getSource()==this.btnThoat)
            this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatCongNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatCongNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatCongNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatCongNhanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatCongNhanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnhDaiDien;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbChucVuNhanVien;
    private javax.swing.JComboBox<String> cbPhongBanNhanVien;
    private com.toedter.calendar.JDateChooser jDateNgayVaoLam;
    private com.toedter.calendar.JDateChooser jdateNgaySinh;
    private javax.swing.JLabel lbAnhDaiDienNhanVien;
    private javax.swing.JLabel lbCapNhatCongNhan;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbErrDiaChi;
    private javax.swing.JLabel lbErrEmail;
    private javax.swing.JLabel lbErrHovaTen;
    private javax.swing.JLabel lbErrMaCongNhan;
    private javax.swing.JLabel lbErrSoCCCD;
    private javax.swing.JLabel lbErrSoDienThoai;
    private javax.swing.JLabel lbExitModal;
    private javax.swing.JLabel lbGachChanDiaChiNhanVien1;
    private javax.swing.JLabel lbGachChanEmailNhanVien;
    private javax.swing.JLabel lbGachChanHoVaTenNhanVien;
    private javax.swing.JLabel lbGachChanMaNhanVien;
    private javax.swing.JLabel lbGachChanSoCCCDNhanVien;
    private javax.swing.JLabel lbGachChanSoDienThoaiNhanVien;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoVaTen;
    private javax.swing.JLabel lbMaCongNhan;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbNgayVaoLam;
    private javax.swing.JLabel lbSoCCCD;
    private javax.swing.JLabel lbSoDienThoaiNhanVien;
    private javax.swing.JLabel lbToNhom;
    private CustomView.PanelBorder panelBorder1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMaCongNha;
    private javax.swing.JTextField txtSoCCCD;
    private javax.swing.JTextField txtSoDienThoaiNhanVien;
    // End of variables declaration//GEN-END:variables
}
