/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ChamCongCongNhan_DAO;
import DAO.ChamCongNhanVien_DAO;
import Entity.ChamCongNhanVien;
import com.sun.org.apache.xerces.internal.util.MessageFormatter;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author December
 */
public class ChiTietLuongNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietLuongCongNhan
     */
    public ChiTietLuongNhanVien(String maNhanVien, String hoVaTen, String tongTien, String thang, String nam) {
        initComponents();
        execute();
        lblValueMaNhanVien.setText(maNhanVien);
        lblValueHoVaTen.setText(hoVaTen);
        lblValueTongTien.setText(tongTien);
        lblTitle.setText("Chi tiết lương nhân viên trong tháng " + thang + "-" + nam);
        taiDuLieuLenBangChiTietLuong(maNhanVien, thang, nam, tongTien);
    }

    private void execute() {
        Container c = this.getContentPane();
        c.setBackground(Color.white);

    }

    public void taiDuLieuLenBangChiTietLuong(String maNhanVien, String thang, String nam, String tongTien) {
        DefaultTableModel model = (DefaultTableModel) tblChiTietLuongNhanVien.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        ChamCongNhanVien_DAO chamCongDao = new ChamCongNhanVien_DAO();
        ArrayList<ChamCongNhanVien> chamCongList = chamCongDao.layDanhSachChamCongTheoNhanVienThangNam(maNhanVien, thang, nam);
        for (ChamCongNhanVien chamCong : chamCongList) {
            model.addRow(new Object[]{model.getRowCount() + 1, chamCong.getNgayChamCong(), chamCong.getCaLam(), chamCong.getTrangThaiDiLam(), chamCong.getGioDiLam()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietLuongNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblValueMaNhanVien = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblValueHoVaTen = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblValueTongTien = new javax.swing.JLabel();
        btnXuatBaoCao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tblChiTietLuongNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblChiTietLuongNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Ngày làm", "Ca làm", "Trạng thái", "Giờ đi làm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietLuongNhanVien.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane1.setViewportView(tblChiTietLuongNhanVien);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 250));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValueMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValueMaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValueMaNhanVien.setText("NV001");
        jPanel2.add(lblValueMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 270, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Họ và tên:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 40));

        lblValueHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValueHoVaTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValueHoVaTen.setText("Nguyễn Van A");
        jPanel2.add(lblValueHoVaTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 300, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Mã nhân viên");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Tổng tiền nhận:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 130, 40));

        lblValueTongTien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValueTongTien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValueTongTien.setText("1000000000000 vnd");
        jPanel2.add(lblValueTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 300, 40));

        btnXuatBaoCao.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXuatBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/update.png"))); // NOI18N
        btnXuatBaoCao.setText("Xuất báo cáo");
        btnXuatBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBaoCaoActionPerformed(evt);
            }
        });
        jPanel2.add(btnXuatBaoCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 60, 50));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chi tiết lương nhân viên trong tháng");
        jPanel2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 840, 70));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1010, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBaoCaoActionPerformed
        MessageFormat header = new MessageFormat(lblTitle.getText());
        MessageFormat footer = new MessageFormat("Nhóm 27");
        try {
            tblChiTietLuongNhanVien.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            e.getMessage();
        }

//        btnXuatBaoCao.setVisible(false);
//        PrinterJob job = PrinterJob.getPrinterJob();
//            job.setJobName("Print Data");
//            
//            job.setPrintable(new Printable(){
//            public int print(Graphics pg,PageFormat pf, int pageNum){
//                    pf.setOrientation(PageFormat.LANDSCAPE);
//                 if(pageNum>0){
//                    return Printable.NO_SUCH_PAGE;
//                }
//                
//                Graphics2D g2 = (Graphics2D)pg;
//                g2.translate(pf.getImageableX(), pf.getImageableY());
//                g2.scale(0.24,0.24);
//                
//                jPanel1.paint(g2);
////          
//               
//                return Printable.PAGE_EXISTS;
//                         
//                
//            }
//    });
//         
//        boolean ok = job.printDialog();
//        if(ok){
//        try{
//            
//        job.print();
//        }
//        catch (PrinterException ex){}
//        }
//          btnXuatBaoCao.setVisible(true);
    }//GEN-LAST:event_btnXuatBaoCaoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietLuongNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ChiTietLuongNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatBaoCao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValueHoVaTen;
    private javax.swing.JLabel lblValueMaNhanVien;
    private javax.swing.JLabel lblValueTongTien;
    private javax.swing.JTable tblChiTietLuongNhanVien;
    // End of variables declaration//GEN-END:variables
}
