/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.CongNhan_DAO;
import DAO.NhanVien_DAO;
import Entity.CongNhan;
import Entity.NhanVien;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author December
 */
public class LayMatKhauView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    private NhanVien_DAO nhanVien_DAO;
    private CongNhan_DAO congNhan_DAO;
    private ArrayList<String> ngonNguList;

    public LayMatKhauView() {
        ngonNguList = new ArrayList<>();
        ngonNguList.add("./config/VietNam.properties");
        ngonNguList.add("./config/English.properties");

        initComponents();
        gui();
        try {
            ConnectionDB.ConnectDB.getInstance().connect();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        congNhan_DAO = new CongNhan_DAO();
        nhanVien_DAO = new NhanVien_DAO();
    }

    public void gui() {
        this.txtMatKhauMoi.setBackground(new Color(0, 0, 0, 1));
        this.txtXacNhanMatKhau.setBackground(new Color(0, 0, 0, 1));
        //    this.txtOTP.setBackground(new Color(0, 0, 0, 1));
    }

    public void caiDatNgonNguChoView(String fileName) throws FileNotFoundException, IOException {
        FileInputStream fis = new FileInputStream(fileName);
        Properties prop = new Properties();
        prop.load(fis);
        lblQuenMatKhau.setText(prop.getProperty("Login_lblTieuDeDangNhap"));
        lblXacNhanMatKhau.setText(prop.getProperty("Login_lblMatKhau"));
        lblQuenMatKhau.setText(prop.getProperty("Login_lblQuenMatKhau"));
        btnXacNhan.setText(prop.getProperty("Login_btnDangNhap"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblQuenMatKhau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblXacNhanMatKhau = new javax.swing.JLabel();
        disableXacNhanMatKhau = new javax.swing.JLabel();
        showXacNhanMatKhau = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        lbPassword02 = new javax.swing.JLabel();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();
        lblMatKhauMoi = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        lbPassword3 = new javax.swing.JLabel();
        disableMatKhauMoi = new javax.swing.JLabel();
        showMatKhauMoi = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên tài khoản:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_user_20px_1.png"))); // NOI18N

        jLabel8.setText("_______________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 57, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau.setText("Quên mật khẩu");
        lblQuenMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 480, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hello! Let's get started");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 70, 550, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        lblXacNhanMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblXacNhanMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblXacNhanMatKhau.setText("Xác nhận mật khẩu");
        jPanel2.add(lblXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 360, -1));

        disableXacNhanMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disableXacNhanMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disableXacNhanMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableXacNhanMatKhauMouseClicked(evt);
            }
        });
        jPanel2.add(disableXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 30, -1));

        showXacNhanMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_eye_20px_1.png"))); // NOI18N
        showXacNhanMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showXacNhanMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showXacNhanMatKhauMouseClicked(evt);
            }
        });
        jPanel2.add(showXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 31, -1));

        btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(0, 102, 102));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel2.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 405, 47));

        lbPassword02.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword02.setText("_____________________________________________________");
        jPanel2.add(lbPassword02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 378, -1));

        txtXacNhanMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtXacNhanMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txtXacNhanMatKhau.setBorder(null);
        jPanel2.add(txtXacNhanMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 360, 30));

        lblMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMatKhauMoi.setForeground(new java.awt.Color(255, 255, 255));
        lblMatKhauMoi.setText("Mật khẩu mới");
        jPanel2.add(lblMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 360, -1));

        txtMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMatKhauMoi.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhauMoi.setBorder(null);
        jPanel2.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 360, 30));

        lbPassword3.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword3.setText("_____________________________________________________");
        jPanel2.add(lbPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 378, -1));

        disableMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disableMatKhauMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disableMatKhauMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMatKhauMoiMouseClicked(evt);
            }
        });
        jPanel2.add(disableMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 30, -1));

        showMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_eye_20px_1.png"))); // NOI18N
        showMatKhauMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showMatKhauMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMatKhauMoiMouseClicked(evt);
            }
        });
        jPanel2.add(showMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 31, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 390));

        setSize(new java.awt.Dimension(551, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void showXacNhanMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showXacNhanMatKhauMouseClicked
        this.txtXacNhanMatKhau.setEchoChar((char) 8226);
        this.disableXacNhanMatKhau.setVisible(true);
        this.showXacNhanMatKhau.setVisible(false);
    }//GEN-LAST:event_showXacNhanMatKhauMouseClicked

    private void disableXacNhanMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableXacNhanMatKhauMouseClicked
        this.txtXacNhanMatKhau.setEchoChar((char) 0);
        this.disableXacNhanMatKhau.setVisible(false);
        this.showXacNhanMatKhau.setVisible(true);
    }//GEN-LAST:event_disableXacNhanMatKhauMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked
    private void disableMatKhauMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMatKhauMoiMouseClicked
        this.txtMatKhauMoi.setEchoChar((char) 0);
        this.disableMatKhauMoi.setVisible(false);
        this.showMatKhauMoi.setEnabled(true);
    }//GEN-LAST:event_disableMatKhauMoiMouseClicked

    private void showMatKhauMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMatKhauMoiMouseClicked
        this.txtMatKhauMoi.setEchoChar((char) 8226);
        this.disableMatKhauMoi.setVisible(true);
        this.showMatKhauMoi.setEnabled(false);
    }//GEN-LAST:event_showMatKhauMoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayMatKhauView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayMatKhauView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayMatKhauView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayMatKhauView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayMatKhauView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel disableMatKhauMoi;
    private javax.swing.JLabel disableXacNhanMatKhau;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbPassword02;
    private javax.swing.JLabel lbPassword3;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblXacNhanMatKhau;
    private javax.swing.JLabel showMatKhauMoi;
    private javax.swing.JLabel showXacNhanMatKhau;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
