/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.CongNhan_DAO;
import DAO.NhanVien_DAO;
import Entity.CongNhan;
import Entity.NhanVien;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author December
 */
public class NhapMaXacNhanView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    private NhanVien_DAO nhanVien_DAO;
    private CongNhan_DAO congNhan_DAO;
    private ArrayList<String> ngonNguList;

    public NhapMaXacNhanView() {
        ngonNguList = new ArrayList<>();
        ngonNguList.add("./config/VietNam.properties");
        ngonNguList.add("./config/English.properties");

        initComponents();
        gui();
        try {
            ConnectionDB.ConnectDB.getInstance().connect();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        congNhan_DAO = new CongNhan_DAO();
        nhanVien_DAO = new NhanVien_DAO();
    }

    public void gui() {
        this.txtNhapMaXacNhan.setBackground(new Color(0, 0, 0, 1));
        //    this.txtOTP.setBackground(new Color(0, 0, 0, 1));
    }

    public void caiDatNgonNguChoView(String fileName) throws FileNotFoundException, IOException {
        FileInputStream fis = new FileInputStream(fileName);
        Properties prop = new Properties();
        prop.load(fis);
        lblQuenMatKhau.setText(prop.getProperty("Login_lblTieuDeDangNhap"));
        lblQuenMatKhau.setText(prop.getProperty("Login_lblQuenMatKhau"));
        btnXacNhan.setText(prop.getProperty("Login_btnDangNhap"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblQuenMatKhau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        lblGuiMa = new javax.swing.JLabel();
        txtNhapMaXacNhan = new javax.swing.JPasswordField();
        lbPassword3 = new javax.swing.JLabel();
        lblNhapMaXacNhan = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên tài khoản:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_user_20px_1.png"))); // NOI18N

        jLabel8.setText("_______________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 57, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau.setText("Nhập mã");
        lblQuenMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 420, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hello! Let's get started");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 70, 550, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(0, 102, 102));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel2.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 405, 47));

        lblGuiMa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGuiMa.setForeground(new java.awt.Color(255, 255, 255));
        lblGuiMa.setText("Gửi mã....");
        jPanel2.add(lblGuiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 360, -1));

        txtNhapMaXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNhapMaXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        txtNhapMaXacNhan.setBorder(null);
        jPanel2.add(txtNhapMaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 360, 30));

        lbPassword3.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword3.setText("______________________________________________________________");
        jPanel2.add(lbPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 430, -1));

        lblNhapMaXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNhapMaXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapMaXacNhan.setText("Nhập mã xác nhận:");
        jPanel2.add(lblNhapMaXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 360, -1));

        lblReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8-prev-30.png"))); // NOI18N
        lblReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnMouseClicked(evt);
            }
        });
        jPanel2.add(lblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        setSize(new java.awt.Dimension(551, 304));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseClicked
        this.dispose();
        new QuenMatKhauView().setVisible(true);
    }//GEN-LAST:event_lblReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapMaXacNhanView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapMaXacNhanView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapMaXacNhanView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapMaXacNhanView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapMaXacNhanView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbPassword3;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGuiMa;
    private javax.swing.JLabel lblNhapMaXacNhan;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JPasswordField txtNhapMaXacNhan;
    // End of variables declaration//GEN-END:variables
}
