/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import ConnectionDB.ConnectDB;
import DAO.CongNhan_DAO;
import DAO.NhanVien_DAO;
import Entity.BangLuongCongNhan;
import Entity.CongNhan;
import Entity.NhanVien;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author December
 */
public class QuenMatKhauView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    private NhanVien_DAO nhanVien_DAO;
    private CongNhan_DAO congNhan_DAO;
    private ArrayList<String> ngonNguList;

    public QuenMatKhauView() {
        ngonNguList = new ArrayList<>();
        ngonNguList.add("./config/VietNam.properties");
        ngonNguList.add("./config/English.properties");
        initComponents();
        gui();
        try {
            ConnectionDB.ConnectDB.getInstance().connect();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        congNhan_DAO = new CongNhan_DAO();
        nhanVien_DAO = new NhanVien_DAO();
    }

    public void caiDatNgonNguChoView(String fileName) throws FileNotFoundException, IOException {
        FileInputStream fis = new FileInputStream(fileName);
        Properties prop = new Properties();
        prop.load(fis);
//        lblTieuDeDangNhap.setText(prop.getProperty("Login_lblTieuDeDangNhap"));
//        lblTenDangNhap.setText(prop.getProperty("Login_lblTenDangNhap"));
//        lblMatKhau.setText(prop.getProperty("Login_lblMatKhau"));
//        btnDangNhap.setText(prop.getProperty("Login_btnDangNhap"));
    }

    public void gui() {
        this.txtDangNhap.setBackground(new Color(0, 0, 0, 1));
        this.txtSoDienThoaiDangKy.setBackground(new Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblQuenMatKhau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        lblSoDienThoaiDangKy = new javax.swing.JLabel();
        lbUserName2 = new javax.swing.JLabel();
        btnGuiMa = new javax.swing.JButton();
        txtSoDienThoaiDangKy = new javax.swing.JTextField();
        lbPassword02 = new javax.swing.JLabel();
        txtDangNhap = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên tài khoản:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_user_20px_1.png"))); // NOI18N

        jLabel8.setText("_______________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 57, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau.setText("Quên mật khẩu");
        lblQuenMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 400, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hello! Let's get started");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 70, 500, -1));

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        lblTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTenDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblTenDangNhap.setText("Tên đăng nhập");
        jPanel2.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 360, -1));

        lbIcon.setForeground(new java.awt.Color(255, 255, 255));
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/icons8_user_20px_1.png"))); // NOI18N
        lbIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 36));

        lblSoDienThoaiDangKy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSoDienThoaiDangKy.setForeground(new java.awt.Color(255, 255, 255));
        lblSoDienThoaiDangKy.setText("Số điện thoại đăng ký");
        jPanel2.add(lblSoDienThoaiDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 360, -1));

        lbUserName2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbUserName2.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName2.setText("______________________________________________");
        jPanel2.add(lbUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnGuiMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuiMa.setForeground(new java.awt.Color(0, 102, 102));
        btnGuiMa.setText("Xác nhận");
        btnGuiMa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMaActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuiMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 405, 47));

        txtSoDienThoaiDangKy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSoDienThoaiDangKy.setForeground(new java.awt.Color(255, 255, 255));
        txtSoDienThoaiDangKy.setBorder(null);
        txtSoDienThoaiDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiDangKyActionPerformed(evt);
            }
        });
        jPanel2.add(txtSoDienThoaiDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 360, 30));

        lbPassword02.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbPassword02.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword02.setText("__________________________________________________________________________");
        jPanel2.add(lbPassword02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 378, -1));

        txtDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        txtDangNhap.setBorder(null);
        txtDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDangNhapActionPerformed(evt);
            }
        });
        jPanel2.add(txtDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 360, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 430));

        setSize(new java.awt.Dimension(551, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMaActionPerformed
        String maNhanVien = this.txtDangNhap.getText();
        String soDitenThoai = this.txtSoDienThoaiDangKy.getText();
        PreparedStatement stm = null;
        try {
            ConnectDB.getInstance();
            Connection con = ConnectDB.getConnection();
            String truyVan = "SELECT * FROM BangLuongCongNhan where maCongNhan = ?";
            stm = con.prepareStatement(truyVan);
//            stm.setString(1, maCongNhan);
            ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                String maBangLuong = rs.getString("maBangLuong");
                String maCongNhanOb = rs.getString("maCongNhan");
                Date ngayTinh = rs.getDate("ngayTinh");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        this.dispose();
        new NhapMaXacNhanView().setVisible(true);
    }//GEN-LAST:event_btnGuiMaActionPerformed

    private void txtSoDienThoaiDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiDangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiDangKyActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDangNhapActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhauView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbPassword02;
    private javax.swing.JLabel lbUserName2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblSoDienThoaiDangKy;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JTextField txtDangNhap;
    private javax.swing.JTextField txtSoDienThoaiDangKy;
    // End of variables declaration//GEN-END:variables
}
