/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.io.File;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Student
 */
public class ThemNhanVienView extends javax.swing.JFrame {

    /**
     * Creates new form modalThemNhanSuView
     */
    public ThemNhanVienView() {
        initComponents();
        init();
    }

    public void init() {
        this.txtMaNhanVien.setText("");
        this.lbErrMaNhanVien.setText("");
        this.txtHoVaTenNhanVien.setText("");
        this.lbErrHoVaTenNhanVien.setText("");
        this.txtSoCCCDNhanVien.setText("");
        this.lbErrSoCCCDNhanVien.setText("");
        this.txtEmailNhanVien.setText("");
        this.lbErrEmailNhanVien.setText("");
        this.txtSoDienThoaiNhanVien.setText("");
        this.lbErrSoDienThoaiNhanVien.setText("");
        this.lbErrSoCCCDNhanVien.setText("");
        this.txtDiaChiThuongChuNhanVien.setText("");
        this.lbErrDiaChiThuongChuNhanVien.setText("");
        this.rdNam.setSelected(true);
        this.txtDiaChiThuongChuNhanVien.setText("");
        this.txtLuongNhanVien.setText("");
        this.lbErrLuongNhanVien.setText("");

        this.txtMaNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtHoVaTenNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtSoCCCDNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtEmailNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtSoDienThoaiNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtDiaChiThuongChuNhanVien.setBackground(new Color(0, 0, 0, 1));
        this.txtLuongNhanVien.setBackground(new Color(0,0,0,1));
        
        ButtonGroup btngroup = new ButtonGroup();
        btngroup.add(this.rdNam);
        btngroup.add(this.rdNu);
        
        
        this.jDateNgayVaoLam.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder1 = new CustomView.PanelBorder();
        lbTieuDeCapNhatNhanVien = new javax.swing.JLabel();
        lbExitModal = new javax.swing.JLabel();
        lbMaNhanVien = new javax.swing.JLabel();
        lbGachChanMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        lbErrMaNhanVien = new javax.swing.JLabel();
        lbHoVatenNhanVien = new javax.swing.JLabel();
        txtHoVaTenNhanVien = new javax.swing.JTextField();
        lbGachChanHoVaTenNhanVien = new javax.swing.JLabel();
        lbAnhDaiDienNhanVien = new javax.swing.JLabel();
        lbErrHoVaTenNhanVien = new javax.swing.JLabel();
        lbSoCCCDNhanVien = new javax.swing.JLabel();
        txtSoCCCDNhanVien = new javax.swing.JTextField();
        lbGachChanSoCCCDNhanVien = new javax.swing.JLabel();
        btnAnhDaiDienNhanVien = new javax.swing.JButton();
        lbErrSoCCCDNhanVien = new javax.swing.JLabel();
        lbEmailNhanVien = new javax.swing.JLabel();
        lbGachChanEmailNhanVien = new javax.swing.JLabel();
        txtEmailNhanVien = new javax.swing.JTextField();
        lbSoDienThoaiNhanVien = new javax.swing.JLabel();
        lbErrEmailNhanVien = new javax.swing.JLabel();
        txtSoDienThoaiNhanVien = new javax.swing.JTextField();
        lbGachChanSoDienThoaiNhanVien = new javax.swing.JLabel();
        lbErrSoDienThoaiNhanVien = new javax.swing.JLabel();
        lbDiaChiThuongChuNhanVien = new javax.swing.JLabel();
        txtDiaChiThuongChuNhanVien = new javax.swing.JTextField();
        lbErrDiaChiThuongChuNhanVien = new javax.swing.JLabel();
        lbGachChanDiaChiNhanVien1 = new javax.swing.JLabel();
        lbLuongNhanVien = new javax.swing.JLabel();
        txtLuongNhanVien = new javax.swing.JTextField();
        lbErrLuongNhanVien = new javax.swing.JLabel();
        lbGachChanDiaChiNhanVien = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jdateNgaySinh = new com.toedter.calendar.JDateChooser();
        lbNgaySinhNhanVien = new javax.swing.JLabel();
        lbPhongBanNhanVien = new javax.swing.JLabel();
        cbPhongBanNhanVien = new javax.swing.JComboBox<>();
        cbChucVuNhanVien = new javax.swing.JComboBox<>();
        lbChucVuNhanVien = new javax.swing.JLabel();
        lbNgayVaoLamNhanVien = new javax.swing.JLabel();
        jDateNgayVaoLam = new com.toedter.calendar.JDateChooser();
        btnLuuNhanVien = new javax.swing.JButton();
        btnThoatNhanVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(204, 102, 255));

        lbTieuDeCapNhatNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbTieuDeCapNhatNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieuDeCapNhatNhanVien.setText("Thêm nhân viên");
        panelBorder1.add(lbTieuDeCapNhatNhanVien);
        lbTieuDeCapNhatNhanVien.setBounds(40, 10, 620, 50);

        lbExitModal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/close.png"))); // NOI18N
        lbExitModal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExitModal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitModalMouseClicked(evt);
            }
        });
        panelBorder1.add(lbExitModal);
        lbExitModal.setBounds(660, 20, 30, 30);

        lbMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMaNhanVien.setText("Mã nhân viên:");
        panelBorder1.add(lbMaNhanVien);
        lbMaNhanVien.setBounds(200, 90, 180, 18);

        lbGachChanMaNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanMaNhanVien);
        lbGachChanMaNhanVien.setBounds(380, 100, 273, 16);

        txtMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaNhanVien.setText("jTextField1");
        txtMaNhanVien.setBorder(null);
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtMaNhanVien);
        txtMaNhanVien.setBounds(380, 90, 270, 20);

        lbErrMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrMaNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrMaNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrMaNhanVien);
        lbErrMaNhanVien.setBounds(380, 120, 230, 20);

        lbHoVatenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbHoVatenNhanVien.setText("Họ và tên:");
        panelBorder1.add(lbHoVatenNhanVien);
        lbHoVatenNhanVien.setBounds(200, 150, 180, 20);

        txtHoVaTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtHoVaTenNhanVien.setText("jTextField1");
        txtHoVaTenNhanVien.setBorder(null);
        txtHoVaTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoVaTenNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtHoVaTenNhanVien);
        txtHoVaTenNhanVien.setBounds(380, 150, 270, 20);

        lbGachChanHoVaTenNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanHoVaTenNhanVien);
        lbGachChanHoVaTenNhanVien.setBounds(380, 160, 273, 16);

        lbAnhDaiDienNhanVien.setBackground(new java.awt.Color(153, 0, 0));
        lbAnhDaiDienNhanVien.setForeground(new java.awt.Color(255, 0, 51));
        lbAnhDaiDienNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/female.png"))); // NOI18N
        panelBorder1.add(lbAnhDaiDienNhanVien);
        lbAnhDaiDienNhanVien.setBounds(20, 130, 140, 160);

        lbErrHoVaTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrHoVaTenNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrHoVaTenNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrHoVaTenNhanVien);
        lbErrHoVaTenNhanVien.setBounds(380, 180, 230, 18);

        lbSoCCCDNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbSoCCCDNhanVien.setText("Số CCCD:");
        panelBorder1.add(lbSoCCCDNhanVien);
        lbSoCCCDNhanVien.setBounds(200, 210, 170, 18);

        txtSoCCCDNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSoCCCDNhanVien.setText("jTextField1");
        txtSoCCCDNhanVien.setBorder(null);
        txtSoCCCDNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoCCCDNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtSoCCCDNhanVien);
        txtSoCCCDNhanVien.setBounds(380, 210, 270, 20);

        lbGachChanSoCCCDNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanSoCCCDNhanVien);
        lbGachChanSoCCCDNhanVien.setBounds(380, 220, 273, 16);

        btnAnhDaiDienNhanVien.setText("Ảnh đại diện");
        btnAnhDaiDienNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnhDaiDienNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhDaiDienNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(btnAnhDaiDienNhanVien);
        btnAnhDaiDienNhanVien.setBounds(30, 300, 103, 25);

        lbErrSoCCCDNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrSoCCCDNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrSoCCCDNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrSoCCCDNhanVien);
        lbErrSoCCCDNhanVien.setBounds(380, 240, 230, 18);

        lbEmailNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbEmailNhanVien.setText("Email:");
        panelBorder1.add(lbEmailNhanVien);
        lbEmailNhanVien.setBounds(200, 270, 180, 18);

        lbGachChanEmailNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanEmailNhanVien);
        lbGachChanEmailNhanVien.setBounds(380, 280, 273, 16);

        txtEmailNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmailNhanVien.setText("jTextField1");
        txtEmailNhanVien.setBorder(null);
        txtEmailNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtEmailNhanVien);
        txtEmailNhanVien.setBounds(380, 270, 270, 20);

        lbSoDienThoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbSoDienThoaiNhanVien.setText("Số điện thoại");
        panelBorder1.add(lbSoDienThoaiNhanVien);
        lbSoDienThoaiNhanVien.setBounds(200, 330, 180, 18);

        lbErrEmailNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrEmailNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrEmailNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrEmailNhanVien);
        lbErrEmailNhanVien.setBounds(380, 300, 230, 18);

        txtSoDienThoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSoDienThoaiNhanVien.setText("jTextField1");
        txtSoDienThoaiNhanVien.setBorder(null);
        txtSoDienThoaiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtSoDienThoaiNhanVien);
        txtSoDienThoaiNhanVien.setBounds(380, 330, 270, 20);

        lbGachChanSoDienThoaiNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanSoDienThoaiNhanVien);
        lbGachChanSoDienThoaiNhanVien.setBounds(380, 340, 273, 16);

        lbErrSoDienThoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrSoDienThoaiNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrSoDienThoaiNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrSoDienThoaiNhanVien);
        lbErrSoDienThoaiNhanVien.setBounds(380, 360, 230, 18);

        lbDiaChiThuongChuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbDiaChiThuongChuNhanVien.setText("Địa chỉ thường chú:");
        panelBorder1.add(lbDiaChiThuongChuNhanVien);
        lbDiaChiThuongChuNhanVien.setBounds(200, 390, 180, 18);

        txtDiaChiThuongChuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDiaChiThuongChuNhanVien.setText("jTextField1");
        txtDiaChiThuongChuNhanVien.setBorder(null);
        txtDiaChiThuongChuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiThuongChuNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtDiaChiThuongChuNhanVien);
        txtDiaChiThuongChuNhanVien.setBounds(380, 390, 270, 20);

        lbErrDiaChiThuongChuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrDiaChiThuongChuNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrDiaChiThuongChuNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrDiaChiThuongChuNhanVien);
        lbErrDiaChiThuongChuNhanVien.setBounds(380, 420, 230, 18);

        lbGachChanDiaChiNhanVien1.setText("_______________________________________");
        panelBorder1.add(lbGachChanDiaChiNhanVien1);
        lbGachChanDiaChiNhanVien1.setBounds(380, 400, 273, 16);

        lbLuongNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbLuongNhanVien.setText("Lương thỏa thuận:");
        panelBorder1.add(lbLuongNhanVien);
        lbLuongNhanVien.setBounds(200, 450, 180, 18);

        txtLuongNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtLuongNhanVien.setText("jTextField1");
        txtLuongNhanVien.setBorder(null);
        txtLuongNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(txtLuongNhanVien);
        txtLuongNhanVien.setBounds(380, 450, 270, 20);

        lbErrLuongNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbErrLuongNhanVien.setForeground(new java.awt.Color(204, 0, 0));
        lbErrLuongNhanVien.setText("đây là dòng thông báo lỗi");
        panelBorder1.add(lbErrLuongNhanVien);
        lbErrLuongNhanVien.setBounds(380, 480, 230, 18);

        lbGachChanDiaChiNhanVien.setText("_______________________________________");
        panelBorder1.add(lbGachChanDiaChiNhanVien);
        lbGachChanDiaChiNhanVien.setBounds(380, 460, 273, 16);

        lbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbGioiTinh.setText("Giới tính:");
        panelBorder1.add(lbGioiTinh);
        lbGioiTinh.setBounds(200, 510, 180, 20);

        rdNam.setText("Nam");
        rdNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });
        panelBorder1.add(rdNam);
        rdNam.setBounds(380, 510, 60, 25);

        rdNu.setText("Nữ");
        rdNu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed(evt);
            }
        });
        panelBorder1.add(rdNu);
        rdNu.setBounds(470, 510, 60, 25);

        jdateNgaySinh.setDateFormatString("yyyy-MM-dd");
        panelBorder1.add(jdateNgaySinh);
        jdateNgaySinh.setBounds(380, 550, 270, 30);

        lbNgaySinhNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgaySinhNhanVien.setText("Ngày sinh:");
        panelBorder1.add(lbNgaySinhNhanVien);
        lbNgaySinhNhanVien.setBounds(200, 560, 120, 18);

        lbPhongBanNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbPhongBanNhanVien.setText("Phòng ban:");
        panelBorder1.add(lbPhongBanNhanVien);
        lbPhongBanNhanVien.setBounds(200, 590, 130, 30);

        cbPhongBanNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng tài chính", "Phòng kinh doanh", "Phòng nhân sự" }));
        cbPhongBanNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBorder1.add(cbPhongBanNhanVien);
        cbPhongBanNhanVien.setBounds(380, 590, 270, 30);

        cbChucVuNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên" }));
        cbChucVuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbChucVuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChucVuNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(cbChucVuNhanVien);
        cbChucVuNhanVien.setBounds(380, 630, 270, 30);

        lbChucVuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbChucVuNhanVien.setText("Chức vụ:");
        panelBorder1.add(lbChucVuNhanVien);
        lbChucVuNhanVien.setBounds(200, 630, 120, 30);

        lbNgayVaoLamNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgayVaoLamNhanVien.setText("Ngày vào làm:");
        panelBorder1.add(lbNgayVaoLamNhanVien);
        lbNgayVaoLamNhanVien.setBounds(200, 670, 130, 30);

        jDateNgayVaoLam.setDateFormatString("yyyy-MM-dd");
        panelBorder1.add(jDateNgayVaoLam);
        jDateNgayVaoLam.setBounds(380, 670, 270, 30);

        btnLuuNhanVien.setBackground(new java.awt.Color(39, 174, 96));
        btnLuuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnLuuNhanVien.setText("Lưu");
        btnLuuNhanVien.setBorder(null);
        btnLuuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBorder1.add(btnLuuNhanVien);
        btnLuuNhanVien.setBounds(190, 730, 130, 40);

        btnThoatNhanVien.setBackground(new java.awt.Color(231, 76, 60));
        btnThoatNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThoatNhanVien.setText("Thoát");
        btnThoatNhanVien.setBorder(null);
        btnThoatNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThoatNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatNhanVienActionPerformed(evt);
            }
        });
        panelBorder1.add(btnThoatNhanVien);
        btnThoatNhanVien.setBounds(410, 730, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(719, 796));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed

    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void txtHoVaTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoVaTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoVaTenNhanVienActionPerformed

    private void txtSoCCCDNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoCCCDNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoCCCDNhanVienActionPerformed

    private void txtEmailNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailNhanVienActionPerformed

    private void txtSoDienThoaiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiNhanVienActionPerformed

    private void txtDiaChiThuongChuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiThuongChuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiThuongChuNhanVienActionPerformed

    private void rdNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNuActionPerformed

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNamActionPerformed

    private void cbChucVuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChucVuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChucVuNhanVienActionPerformed

    private void lbExitModalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitModalMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbExitModalMouseClicked

    private void btnAnhDaiDienNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhDaiDienNhanVienActionPerformed
        JFileChooser fileChooser = new JFileChooser("d:");
//        int respone=fileChooser.showOpenDialog(null);
        fileChooser.setCurrentDirectory(new File(".\\src\\image"));
        int respone=fileChooser.showSaveDialog(null);
        if(respone== JFileChooser.APPROVE_OPTION ){
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            System.out.println(file);
            String path = file.toString().split("src")[1].replace('\\', '/');
            System.out.println("path file split: "+file.toString().split("src")[1]);
            this.lbAnhDaiDienNhanVien.setIcon(new ImageIcon(this.getClass().getResource(path)));
            System.out.println(this.lbAnhDaiDienNhanVien.getIcon().toString());
        }
    }//GEN-LAST:event_btnAnhDaiDienNhanVienActionPerformed

    private void txtLuongNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongNhanVienActionPerformed

    private void btnThoatNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatNhanVienActionPerformed
        if(evt.getSource()==this.btnThoatNhanVien)
            this.dispose();
    }//GEN-LAST:event_btnThoatNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNhanVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnhDaiDienNhanVien;
    private javax.swing.JButton btnLuuNhanVien;
    private javax.swing.JButton btnThoatNhanVien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbChucVuNhanVien;
    private javax.swing.JComboBox<String> cbPhongBanNhanVien;
    private com.toedter.calendar.JDateChooser jDateNgayVaoLam;
    private com.toedter.calendar.JDateChooser jdateNgaySinh;
    private javax.swing.JLabel lbAnhDaiDienNhanVien;
    private javax.swing.JLabel lbChucVuNhanVien;
    private javax.swing.JLabel lbDiaChiThuongChuNhanVien;
    private javax.swing.JLabel lbEmailNhanVien;
    private javax.swing.JLabel lbErrDiaChiThuongChuNhanVien;
    private javax.swing.JLabel lbErrEmailNhanVien;
    private javax.swing.JLabel lbErrHoVaTenNhanVien;
    private javax.swing.JLabel lbErrLuongNhanVien;
    private javax.swing.JLabel lbErrMaNhanVien;
    private javax.swing.JLabel lbErrSoCCCDNhanVien;
    private javax.swing.JLabel lbErrSoDienThoaiNhanVien;
    private javax.swing.JLabel lbExitModal;
    private javax.swing.JLabel lbGachChanDiaChiNhanVien;
    private javax.swing.JLabel lbGachChanDiaChiNhanVien1;
    private javax.swing.JLabel lbGachChanEmailNhanVien;
    private javax.swing.JLabel lbGachChanHoVaTenNhanVien;
    private javax.swing.JLabel lbGachChanMaNhanVien;
    private javax.swing.JLabel lbGachChanSoCCCDNhanVien;
    private javax.swing.JLabel lbGachChanSoDienThoaiNhanVien;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoVatenNhanVien;
    private javax.swing.JLabel lbLuongNhanVien;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JLabel lbNgaySinhNhanVien;
    private javax.swing.JLabel lbNgayVaoLamNhanVien;
    private javax.swing.JLabel lbPhongBanNhanVien;
    private javax.swing.JLabel lbSoCCCDNhanVien;
    private javax.swing.JLabel lbSoDienThoaiNhanVien;
    private javax.swing.JLabel lbTieuDeCapNhatNhanVien;
    private CustomView.PanelBorder panelBorder1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTextField txtDiaChiThuongChuNhanVien;
    private javax.swing.JTextField txtEmailNhanVien;
    private javax.swing.JTextField txtHoVaTenNhanVien;
    private javax.swing.JTextField txtLuongNhanVien;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSoCCCDNhanVien;
    private javax.swing.JTextField txtSoDienThoaiNhanVien;
    // End of variables declaration//GEN-END:variables
}
